export interface PinValidationResult {
  errors: string[];
  warnings: string[];
}

/**
 * Normalizes pin string to find numeric parts or standardized names.
 * e.g., "GPIO 21" -> "21", "GPIO15" -> "15", "PA9" -> "PA9", "3V3" -> "3V3"
 */
function normalizePin(pin: string): string {
  const p = pin.trim().toUpperCase();
  if (p.startsWith("GPIO")) {
    return p.replace(/\s+/g, ""); // "GPIO 21" -> "GPIO21"
  }
  return p;
}

function isSdaConnection(u: any): boolean {
  const sig = (u.signalType || "").toUpperCase();
  const pin = (u.toPin || "").toUpperCase();
  return sig === "I2C_SDA" || pin === "SDA" || sig.includes("SDA") || (sig === "I2C" && pin.includes("SDA")) || (sig.includes("I2C") && pin.includes("SDA"));
}

function isSclConnection(u: any): boolean {
  const sig = (u.signalType || "").toUpperCase();
  const pin = (u.toPin || "").toUpperCase();
  return sig === "I2C_SCL" || pin === "SCL" || sig.includes("SCL") || (sig === "I2C" && pin.includes("SCL")) || (sig.includes("I2C") && pin.includes("SCL"));
}

function isSpiSckConnection(u: any): boolean {
  const sig = (u.signalType || "").toUpperCase();
  const pin = (u.toPin || "").toUpperCase();
  return sig.includes("SPI_SCK") || sig.includes("SPI_CLK") || pin === "SCK" || pin === "CLK" || pin === "SCLK";
}

function isSpiMosiConnection(u: any): boolean {
  const sig = (u.signalType || "").toUpperCase();
  const pin = (u.toPin || "").toUpperCase();
  return sig.includes("SPI_MOSI") || pin === "MOSI" || pin === "DIN";
}

function isSpiMisoConnection(u: any): boolean {
  const sig = (u.signalType || "").toUpperCase();
  const pin = (u.toPin || "").toUpperCase();
  return sig.includes("SPI_MISO") || pin === "MISO" || pin === "SO" || pin === "DOUT";
}

/**
 * Validates generated IoT project hardware pin allocation and wiring.
 * 
 * @param connections Connections list generated by AI
 * @param platform MCU platform e.g., 'ESP32' or 'STM32'
 */
export function validateProjectHardware(connections: any[], platform: string): PinValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!Array.isArray(connections) || connections.length === 0) {
    return { errors, warnings };
  }

  const isESP32 = platform.toUpperCase().includes("ESP32");
  const isSTM32 = platform.toUpperCase().includes("STM32");

  // 1. PIN COLLISION DETECTION (except power/ground and matching multi-drop buses)
  const pinUsageMap = new Map<string, Array<{ toComponent: string; signalType: string; toPin: string }>>();

  for (const conn of connections) {
    const fromPin = normalizePin(conn.fromPin);
    if (!fromPin) continue;

    // Skip power lines
    if (["3V3", "5V", "GND", "VCC"].includes(fromPin)) {
      continue;
    }

    if (!pinUsageMap.has(fromPin)) {
      pinUsageMap.set(fromPin, []);
    }
    pinUsageMap.get(fromPin)!.push({
      toComponent: conn.toComponent,
      signalType: conn.signalType,
      toPin: conn.toPin
    });
  }

  for (const [pin, usages] of pinUsageMap.entries()) {
    if (usages.length > 1) {
      // Multiple components on same pin. Let's see if it's allowed.
      // Rule: Allowed if and only if it's a shared bus (I2C SDA, I2C SCL, SPI SCK, SPI MOSI, SPI MISO)
      const isSharedBus = 
        usages.every(isSdaConnection) || 
        usages.every(isSclConnection) || 
        usages.every(isSpiSckConnection) || 
        usages.every(isSpiMosiConnection) || 
        usages.every(isSpiMisoConnection);

      if (!isSharedBus) {
        const componentsList = usages.map(u => `"${u.toComponent}" (信号: ${u.signalType}, 引脚: ${u.toPin})`).join(" 与 ");
        errors.push(`引脚冲突：主控引脚 ${pin} 同时被分配给了多个非总线外设或不同类型的总线信号：${componentsList}。每个 GPIO 引脚在同一时间只能连接一个数字/模拟信号源（非总线共享模式）。`);
      }
    }
  }

  // 2. PLATFORM-SPECIFIC CHECKS
  for (const conn of connections) {
    const fromPin = normalizePin(conn.fromPin);
    const toComp = conn.toComponent || "";
    const signalType = conn.signalType || "";
    
    // Identify output/actuation components based on keywords
    const isOutputComponent = 
      toComp.includes("蜂鸣器") || 
      toComp.includes("Buzzer") ||
      toComp.includes("LED") ||
      toComp.includes("继电器") || 
      toComp.includes("Relay") ||
      toComp.includes("舵机") || 
      toComp.includes("Servo") || 
      toComp.includes("电机") ||
      toComp.includes("Motor") ||
      toComp.includes("OLED") ||
      toComp.includes("LCD") ||
      toComp.includes("显示屏") ||
      toComp.includes("Display");

    if (isESP32) {
      // 2.1 ESP32 Input-Only Pins (GPIO34, GPIO35, GPIO36, GPIO39)
      const inputOnlyPins = ["GPIO34", "GPIO35", "GPIO36", "GPIO39"];
      if (inputOnlyPins.includes(fromPin)) {
        if (isOutputComponent || signalType === "PWM" || signalType === "UART_TX") {
          errors.push(`引脚特性错误：ESP32 的 ${fromPin} 是仅输入引脚 (Input-Only)，不能分配给需要驱动输出的设备 "${toComp}"。请选择其他支持输出的 GPIO 引脚。`);
        }
      }

      // 2.2 ESP32 Strapping Pins Warning (GPIO0, GPIO2, GPIO12, GPIO15)
      const strappingPins = ["GPIO0", "GPIO2", "GPIO12", "GPIO15"];
      if (strappingPins.includes(fromPin)) {
        // If connected to sensors/actuators that might pull state during boot
        warnings.push(`启动配置警告：引脚 ${fromPin} 是 ESP32 的启动配置引脚 (Strapping Pin)。请注意，如果外设 "${toComp}" 在上电时将其拉低或拉高，可能会导致 ESP32 无法正常启动或无法进入固件烧录模式。`);
      }
    }

    // 3. ELECTRICAL VOLTAGE SAFETY CHECKS (3.3V MCU vs 5V Signals)
    // Identify 5V outputting sensors/devices
    const is5VDevice = 
      toComp.includes("MQ-2") || 
      toComp.includes("1602") || 
      toComp.includes("继电器") || 
      toComp.includes("Relay") ||
      toComp.includes("蜂鸣器") ||
      toComp.includes("Buzzer") ||
      toComp.includes("舵机") || 
      toComp.includes("Servo");

    if ((isESP32 || isSTM32) && is5VDevice) {
      // Check if it's connected to signal pin
      if (!["VCC", "GND", "3V3", "5V"].includes(fromPin) && (signalType === "GPIO" || signalType === "ADC" || signalType === "PWM")) {
        warnings.push(`电气安全提示：检测到 5V 工作电压的器件 "${toComp}" 连接到了 3.3V 主控的信号线 ${fromPin}。在进行物理硬件连线时，建议在信号线中接入电平转换模块或分压电阻（如 1kΩ 和 2kΩ 组成的电阻分压网络），以防 5V 高电平信号输入导致主控引脚过载烧毁。`);
      }
    }
  }

  return { errors, warnings };
}
