import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  lang: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  zh: {
    // TopNavbar
    brandTitle: "物联网智能生成平台",
    brandSub: "项目生成器",
    signIn: "接入账户",
    signOut: "退出",
    // Sidebar
    workspace: "工作台",
    step1: "1. 需求输入",
    step2: "2. 提示词优化",
    step3: "3. 方案流生成",
    step4: "4. 电路图预览",
    step5: "5. 代码包预览",
    step6: "6. 学习任务评价",
    records: "数据与记录",
    history: "历史生成项目",
    admin: "控制后台管理",
    disclaimerTitle: "接线免责声明",
    disclaimerDesc: "自动生成的接线图与代码仅供原型方案研究使用。实际操作布线、插拔或通电前，务必断电并核对引脚官方原件定义。",
    account: "账户管理",
    quota: "免费 Spark 算力额度",
    // RequirementInput
    greeting: "下午好，",
    inputDesc: "请输入您的物联网系统设计构思，支持传感器、显示、报警、通信等多种场景组合，系统将为您生成硬件接线与完整软件代码。",
    mcuPlatform: "1. 选择主控平台",
    mcuESP32Desc: "支持 Wi-Fi + 蓝牙；运算速度 240MHz 双核。开发效率高，首选无线互联场景。",
    mcuSTM32Desc: "ARM Cortex-M3 架构；高性价比工业控制首选。无原生 Wi-Fi，适合单机/有线场景。",
    designDesc: "2. 描述物联网设计意图",
    placeholderText: "请输入您的方案设想。例如：'我想要制作一个ESP32大棚温湿度检测程序，传感器用DHT22，还要搭载一个I2C OLED小屏用于展示温度。如果温度由于异常原因超过38度，就在引脚接一个蜂鸣器，使其频繁鸣叫。'",
    charCount: "字符",
    aiEngine: "3. 选择智能生成编译器",
    optimizeBtn: "开始优化并锁定方案",
    optimizingBtn: "解析分析中...",
    presetTitle: "典型仿真实验案例",
    sug1_title: "智能农业环境监测系统",
    sug1_desc: "连接温湿度传感器 DHT22 与空气质量传感器 SGP30，实时检测环境参数并通过 I2C OLED 屏幕显示。若温度超过预设阈值，则触发有源蜂鸣器鸣叫报警，并通过无线网络上报至云平台控制台。",
    sug2_title: "工业双路电机与姿态控制器",
    sug2_desc: "通过 I2C 接口读取 MPU6050 六轴陀螺仪姿态数据，通过 PWM 信号控制 L298N 驱动板调节双路直流电机转速，并使用 1.8寸 ST7735 彩色 TFT 屏显示运动姿态状态。",
    sug3_title: "智能声光避障测距仪",
    sug3_desc: "读取 HC-SR04 超声波测距传感器数据，在 TM1637 四位数码管上显示厘米距离。当检测到障碍物距离低于 20cm 时，驱动 SG90 舵机旋转 90 度并鸣叫蜂鸣器发出警告。",
    // PromptOptimize
    optTitle: "提示词优化与方案确认",
    optDesc: "系统已将您的需求转换为结构化提示词，请在下方检查或微调提示词细节，确认后开始生成主板接线图与代码包。",
    rawReq: "原始需求",
    optSpec: "AI 优化后结构化提示词",
    microTuning: "手动微调",
    saveChange: "保存更改",
    generateBtn: "开始生成项目方案",
    generatingBtn: "建立信道中...",
    structHardware: "结构化硬件识别结果",
    propertyMcu: "主控平台",
    propertySensor: "传感器选件",
    propertyDisplay: "显示输出",
    propertyAlert: "执行与报警",
    propertyNetwork: "联网与协议",
    propertyPower: "供电规格",
    optTip: "提示：结构化结果是由 AI 根据原始输入推导得出，如果您对识别的特定细节有异议，可以直接点击左侧的“手动微调”自行更改。",
    stepTitle1: "1. 需求输入",
    stepTitle2: "2. 提示词优化与锁定硬件",
    stepTitle3: "3. 方案生成",
    stepTitle4: "4. 电路接线",
    stepTitle5: "5. 代码包导出",
    // TaskProgress
    progTitle: "方案生成与任务进度",
    progDesc: "实时的多阶计算正在进行中。AI 正在编写固件，并通过物理拓扑设计电路引脚。",
    taskName: "当前任务",
    taskStatus: "运行状态",
    estTime: "任务用时",
    actions: "操作",
    statusGenerating: "正在生成中...",
    statusCompleted: "生成已成功完成",
    statusFailed: "服务连接中断",
    rebuildBtn: "重新建立生成",
    waitSubmit: "请等待进程提交",
    autoSaved: "已自动写入数据库",
    failedAlert: "生成由于错误被迫中止",
    errorLabel: "错误提示:",
    errorDefault: "请确认您的 API Key 无误且账户余额充足。",
    stepsStream: "实实时步骤日志",
    loadingPipe: "正在载入后续管道算力...",
    outputsGauges: "交付部件加载进度",
    architecturePlan: "项目方案设计与选型",
    wiringPinMap: "物理接线拓扑与引脚配准",
    firmwareCodes: "Arduino/C++ 主固件代码",
    zipPackaging: "打包归档并建立信道通道",
    processNotice: "进程状态说明：AI 正在进行分布式求解物理电路连接和 C++ 类驱动方法，请保持窗口开启。",
    // ProjectResults
    buildSuccess: "项目构建方案已生成并导出",
    completed: "已完成",
    copyBtn: "复制方案",
    downloadBtn: "下载 ZIP",
    viewCodeBtn: "浏览及复制代码包",
    schemeTable: "1. 项目方案设计选型表",
    copysuccess: "项目方案设计已复制至剪贴板！",
    tuningTable: "硬件物联连接表",
    tuningDesc: "支持在表格中人工调整主芯片引脚映射，更改将自动在 CAD 走线图上同步自适应绘制。",
    restoreBtn: "复原 AI 默认引脚",
    conflictWarn: "检测到硬件 GPIO 冲突警告",
    conflictDesc: "由于外设引脚配置出现重叠，直接编译烧录将会引发总线碰撞或芯片阻抗击穿，建议通过下拉选择其他安全 IO 引脚进行微调消除冲突：",
    mcuPin: "主芯片引脚",
    peripheral: "对应外设",
    peripheralPin: "外设引脚",
    signalType: "信号类型",
    wireColor: "物理配线颜色",
    collisionTuning: "物理描述与校验标定",
    conflictMessage: "存在引脚独占性冲突：本行正在与其他设备重复绑定在该引脚。请通过下拉框微调。",
    defaultPinDesc: "由芯片与工作外设硬件的信号引脚互连以驱动并操作。",
    bomTabTitle: "元器件采购清单 (BOM)",
    bomTabDesc: "系统根据接线图自动解析出您项目所需的所有核心半导体芯片与外围元器件，支持导出立创商城 BOM 或一键配单一键购齐。",
    bomItemName: "器件名称",
    bomCNumber: "立创商品编号 (C号)",
    bomQuantity: "数量",
    bomPrice: "参考单价",
    bomAction: "采购渠道",
    bomCopyBtn: "一键复制采购清单",
    bomExportBtn: "导出立创 BOM (CSV)",
    bomCopySuccess: "采购清单已成功复制到剪贴板！",
    bomNotice: "提示：您可以点击“导出立创 BOM”下载 CSV，然后上传至立创商城 (https://bom.szlcsc.com/) 即可打包一键购齐。",
    // CodeViewer
    codeTitle: "完整程序代码代码包库",
    codeDesc: "自动解析出的 C++ 引脚配置、传感器驱动包和网络请求实例已经完成编译验证。",
    copyFile: "复制当前文件",
    copySuccessFile: "文件内容已成功复制！",
    downloadZip: "下载完整工程 ZIP",
    viewAllFiles: "查看本包全部文件结构",
    dirTree: "项目文件树",
    copied: "已复制",
    previewPlaceholder: "请选择文件进行预览",
    copyTree: "复制项目树",
    downloadZipBtn: "一键下载 ZIP 代码包",
    treeCopiedAlert: "目录结构已复制！",
    compatNotice: "支持 ARDUINO IDE • ESP-IDF • PLATFORMIO 开箱即用编译",
    // DownloadCenter
    downloadTitle: "学习任务评价",
    downloadDesc: "按照需求分析、器件选型、接口识别、虚拟接线、安全判断、代码理解、工程导出和反思改进的流程，记录学生学习过程并生成教师反馈。",
    noActiveProj: "尚未生成教学项目",
    noActiveProjDesc: "请先在需求输入中生成一个物联网教学项目，系统将自动组织教学支架、工程资源和评价任务。",
    startNewProj: "开始生成教学项目",
    resourcePackTitle: "课件配套工程资源包",
    resourcePackDesc: "包含固件代码、引脚配置、接线说明、README 和工程导出文件，可作为学生任务成果与教师演示材料。",
    zipFilenameDesc: "包含主控配置代码、电路 CAD 映射说明及 Readme 文档",
    ready: "就绪",
    fileCount: "文件总数",
    fileCountVal: "个文件",
    unzipSize: "未压缩尺寸",
    mainPlatform: "主流平台",
    sigVerification: "签名验证",
    shaVerified: "SHA-256 已验证",
    actionDownload: "下载课件工程资源包",
    actionShare: "共享方案链接",
    shareSuccessAlert: "项目共享链接已复制至剪贴板，其他工程人员访问该链接即可实时同步方案结构。",
    stm32Notice: "提示：本系统的 STM32 固件采用了标准外设库 (SPL) 架构，并已为您生成了完整的项目树（包含 platformio.ini、延时、OLED 等无第三方依赖驱动）。您可以直接通过 VSCode 的 PlatformIO 插件打开该目录，即可直接开箱一键编译并烧录至 Blue Pill 硬件中。",
    espNotice: "提示：本系统的固件代码采用标准 C++/Arduino 架构构建，已生成 platformio.ini 配置及完整的源程序结构。您可以直接导入 VSCode CLI (PlatformIO) 或是官方 Arduino IDE，开箱即用。",
    wiringGuideTitle: "实机调试防灾指南",
    wiringGuideDesc: "智能编译器已按照电平协议自动在 IO 口分配引脚。但在开始接实线之前，请务必执行以下安全审计核对，防止板子烧毁：",
    wiringGuideRule1: "严禁混淆 5V 与 3.3V：绝大多数 ESP32 处理模块在 IO 口的承压最高为 3.3V。将 5V 电平直接接到未经电平转换的 GPIO 口可能会造成处理器物理烧损。",
    wiringGuideRule2: "大功耗外设供电隔离：绝不能直接通过主板 3.3V 引脚向大功率舵机、继电器、5050 强光带等供电。必须对这些组件配合外部大功率开关电源并共地。",
    wiringGuideRule3: "电平拉高：I2C 的 SDA 与 SCL 引脚通常要求加挂 4.7kΩ 或 10kΩ 上拉电阻到 3.3V（即使某些开发板带有内置弱上拉）。",
    zipDetailsTitle: "ZIP 归档目录明细",
    boardCompat: "主板兼容",
    i2cRule: "I2C 接线规则",
    standardPinAlloc: "标准引脚分配",
    needModifyPinTitle: "需要修改引脚吗？",
    needModifyPinDesc: "如果您需要重新映射主控板的针脚，可以点击左侧导航栏的【2. 提示词优化】自主改写端口逻辑设定，或在此处向 AI 直接补充新的引脚微调要求。",
    modifyPromptBtn: "微调引脚映射提示词",
    // HistoryList
    confirmDelete: "确认删除此项目的生产方案吗？该操作不可逆。",
    loginAuthTitle: "请先登录授权您的账户",
    loginAuthDesc: "登录后即可利用 Firestore 数据库自动保存所有生成的接线原理图与代码包，实现随时调阅和跨端工作。",
    historyTitle: "历史生成项目方案",
    historyDesc: "您曾经构思和编译的硬件系统设计已经存档在云数据库中。",
    syncCloudBtn: "同步云端",
    syncingBtn: "同步中...",
    loadingHistory: "正在调阅云端数据库结构...",
    noHistory: "没有历史项目",
    noHistoryDesc: "请前往主工作台输入您的第一个需求。项目编译成功后将自动云同步保护。",
    viewSchemeOnBoard: "在主板查看方案",
    deleteHistoryTitle: "删除历史大纲",
    // AdminPanel
    adminTitle: "物联网云平台后台管理系统",
    adminDesc: "配置专家机制匹配的核心主板列表、传感器元器件字典、硬件接线规规制，并查询全系统诊断审计日志。",
    demoEnvironment: "演示调试环境：超管权限处于激活态",
    tabMcus: "1. 平台芯片库",
    tabComponents: "2. 元器件外设库",
    tabRules: "3. 引脚校验接线规",
    tabTemplates: "4. 编译大纲大模板",
    tabAudits: "5. 下载日志与审计",
    tabUsers: "6. 用户账号管理",
    mcuDbNotice: "主芯片数据库决定了生成大纲时，首推的主板硬件名称以及 SDA/SCL 引脚、串口引脚、工作电平等技术规格约束。",
    addMcuBtn: "新增主开发板",
    mcuFormCancel: "取消",
    mcuFormSubmit: "提交保存",
    mcuNameLabel: "芯片型号 *",
    mcuFamilyLabel: "处理器家族",
    mcuSdaLabel: "SDA Pin (I2C)",
    mcuSclLabel: "SCL Pin (I2C)",
    mcuRomLabel: "ROM大小",
    mcuVoltageLabel: "额定供电电平",
    mcuTableColName: "主开发芯片名称",
    mcuTableColFamily: "内核家族",
    mcuTableColPins: "标准 SDA / SCL",
    mcuTableColRom: "闪存存储 ROM",
    mcuTableColVoltage: "系统供电",
    mcuTableColRecom: "专家机制推荐",
    mcuTableColAction: "操作",
    mcuActive: "有效",
    mcuInactive: "禁用",
    deleteMcuTitle: "删除芯片",
    compDbNotice: "管理系统支持匹配的各类物联网外设总表（传感器、显示屏、报警灯等），支持在此录入新购入的传感器规格。",
    addComponentBtn: "新增感元器件",
    compNameLabel: "自定元器件名称 *",
    compTypeLabel: "输入输出类型",
    compCategoryLabel: "物抗类别分类",
    compPinsLabel: "所需物理引脚",
    compVoltageLabel: "额定供电电平",
    compDescLabel: "引脚接法或描述备注",
    compFormSubmit: "保存并入库",
    compTableColName: "物联网外设元器件",
    compTableColCategory: "器件分类",
    compTableColType: "物理信号类型",
    compTableColPins: "引脚消耗",
    compTableColVoltage: "电平适配",
    compTableColDesc: "技术描述备注",
    compTableColStatus: "状态控制",
    compTableColAction: "操作",
    compActive: "运行中",
    compInactive: "禁用",
    deleteCompTitle: "物理移出",
    rulesNoticeTitle: "实时专家引脚纠错核心校验已激活",
    rulesNoticeDesc: "下面列出的规则用于规范大模型提示词优化编译器。发生外挂设备冲突时，系统会按顺次重定向，优先隔离冲突针脚口。",
    rulesEspTitle: "规则一：ESP32 禁用引脚约束",
    rulesEspDesc: "系统严禁在 ESP32 默认引导或内置闪存引脚上配置大传感器，否则极易由于上电电平拉低引发无法烧录。",
    rulesEspList: "• GPIO 12 / MTDI (引导控制，上电须拉低)\n• GPIO 15 / MTDO (调试控制，上电须高电平)\n• GPIO 0 (系统Boot，低电平进入下载状态)\n• GPIO 34-39 (仅限ADC输入引脚，严禁输出)",
    rulesI2cTitle: "规则二：I2C 端口共用隔离",
    rulesI2cDesc: "具有多于两个 I2C 器件（如显示屏 + AHT20 + SGP30）时，系统自动核查各器件的 7 位硬件十六进制寻址，拒绝相同地址组件。",
    rulesI2cList: "• OLED SSD1306 寻址: 0x3C (或 0x3D)\n• BMP280 气压计寻址: 0x76 (或 0x77)\n• AHT20 温湿度寻址: 0x38 (独占不可更改)\n• PCA9685 PWM板寻址: 0x40 (基地址硬编码)",
    templateTitle: "大纲编译 & 代码生成底层程序大骨架",
    templateDesc: "本平台底层通过标准化 Handlebars 微型模板驱动，根据选定的引脚排线自动填充固件 C++ 头文件，保障引脚不发生冲突：",
    auditsNotice: "安全下载审计模块记录了所有用户的 Oauth 凭证验证、ZIP 下载数量、单次编译耗时，用来统计 API 算力的消耗及防爆防刷防盗。",
    auditsTableColUser: "系统用户",
    auditsTableColAction: "动作行为",
    auditsTableColProj: "生成项目工程名",
    auditsTableColPlatform: "物理平台",
    auditsTableColIp: "访问 IP & 地理",
    auditsTableColTime: "编译与操作时间",
    auditsTableColDetail: "编译诊断明细",
    auditsTableColStatus: "状态记录",
    // App empty states
    emptyStateTitle: "暂未载入项目的【{tabTitle}】",
    emptyStateDesc: "您当前没有处于进行中或已被激活的物联网系统项目。请先前往需求输入模块配置一套硬件方案，或者直接加载系统预设的「STM32 智能温室典型仿真实验」进行查阅。",
    emptyStateGoInput: "去【1. 需求输入】填写",
    emptyStateLoadDemo: "加载典型仿真实验",
    demoTitle: "智能温室大棚自动化物联网系统",
  },
  en: {
    // TopNavbar
    brandTitle: "IoT Smart Generator",
    brandSub: "Project Generator",
    signIn: "Sign In",
    signOut: "Sign Out",
    // Sidebar
    workspace: "Workspace",
    step1: "1. Requirement Input",
    step2: "2. Prompt Optimize",
    step3: "3. Generation Progress",
    step4: "4. Schematic Preview",
    step5: "5. Code Package Preview",
    step6: "6. Learning Assessment",
    records: "Records & History",
    history: "History Projects",
    classManagement: "Class Management",
    admin: "Admin Console",
    disclaimerTitle: "Wiring Disclaimer",
    disclaimerDesc: "Generated wiring diagrams and code are for prototyping and research only. Be sure to power off before wiring, inserting, or powering on devices, and check official pin definitions.",
    account: "Account",
    quota: "Free Spark Quota Active",
    // RequirementInput
    greeting: "Good afternoon, ",
    inputDesc: "Enter your IoT design requirements. The system will automatically generate hardware pin routing and compile complete software source code.",
    mcuPlatform: "1. Select MCU Platform",
    mcuESP32Desc: "Supports Wi-Fi + Bluetooth; 240MHz dual-core. High efficiency, preferred for wireless and IoT scenarios.",
    mcuSTM32Desc: "ARM Cortex-M3; cost-effective choice for industrial control. No native Wi-Fi, suitable for standalone control.",
    designDesc: "2. Describe IoT System Design Requirements",
    placeholderText: "Enter your requirements. E.g., 'ESP32 greenhouse sensor system with DHT22 temperature/humidity, OLED 128x64 display. If temperature exceeds 38C, trigger buzzer alarm.'",
    charCount: "chars",
    aiEngine: "3. Choose AI Compiler Engine",
    optimizeBtn: "Optimize & Lock Plan",
    optimizingBtn: "Analyzing...",
    presetTitle: "Simulation Lab Cases",
    sug1_title: "Smart Agriculture IoT Monitor",
    sug1_desc: "Reads DHT22 (temp/humi) and SGP30 (air quality) sensors, displaying status on an I2C OLED screen. Triggers a buzzer alarm on high temperature and uploads records to an IoT cloud platform via wireless networks and MQTT.",
    sug2_title: "Industrial Dual Motor & IMU Controller",
    sug2_desc: "Reads motion telemetry from an MPU6050 six-axis gyroscope, drives dual DC motors via an L298N driver board using PWM duty signals, and displays real-time state on an ST7735 color TFT screen.",
    sug3_title: "Ultrasonic Rangefinder & Obstacle Avoidance",
    sug3_desc: "Uses an HC-SR04 ultrasonic sensor to display distance in centimeters on a TM1637 segment display. Sweeps an SG90 servo 90 degrees and beeps a buzzer when an obstacle is detected within 20cm.",
    // PromptOptimize
    optTitle: "Prompt Optimization & Spec Confirmation",
    optDesc: "The system has compiled your inputs into a structured specification. Review or tune details below, and click Generate to build the schematic and code.",
    rawReq: "Raw Requirements",
    optSpec: "AI-Optimized Specification",
    microTuning: "Manual Tuning",
    saveChange: "Save Changes",
    generateBtn: "Generate Project Scheme",
    generatingBtn: "Establishing compile channel...",
    structHardware: "Structured Hardware Detection",
    propertyMcu: "MCU Platform",
    propertySensor: "Sensors",
    propertyDisplay: "Display",
    propertyAlert: "Alert / Actuator",
    propertyNetwork: "Network Protocol",
    propertyPower: "Power Input",
    optTip: "Note: The structured properties are derived from raw inputs. You can click 'Manual Tuning' on the left to modify details directly.",
    stepTitle1: "1. Requirement Input",
    stepTitle2: "2. Prompt Optimization",
    stepTitle3: "3. Compile & Generate",
    stepTitle4: "4. Schematic Routing",
    stepTitle5: "5. Code Package Export",
    // TaskProgress
    progTitle: "Generation Progress Log",
    progDesc: "Calling AI IoT Compiler. Generating schematic wiring maps and compiling code files. Takes 15-20 seconds.",
    taskName: "Task Name",
    taskStatus: "Status",
    estTime: "Elapsed Time",
    actions: "Actions",
    statusGenerating: "Generating...",
    statusCompleted: "Completed Successfully",
    statusFailed: "Connection Interrupted",
    rebuildBtn: "Rebuild Generation",
    waitSubmit: "Please wait for submission",
    autoSaved: "Auto-saved to database",
    failedAlert: "Compilation Failed",
    errorLabel: "Error message:",
    errorDefault: "Please verify your API Key and account status.",
    stepsStream: "Real-time Steps Stream",
    loadingPipe: "Loading backend resource pipelines...",
    outputsGauges: "Component Outputs Gauges",
    architecturePlan: "Architecture Plan",
    wiringPinMap: "Wiring Pin Map",
    firmwareCodes: "Firmware Codes",
    zipPackaging: "Zip Packaging",
    processNotice: "Process: AI is solving physical connections and driver classes dynamically. Keep this window open.",
    // ProjectResults
    buildSuccess: "Project Schematic & Code Generated Successfully",
    completed: "Completed",
    copyBtn: "Copy Scheme",
    downloadBtn: "Download ZIP",
    viewCodeBtn: "View & Copy Code Pack",
    schemeTable: "1. Hardware Spec Sheet",
    copysuccess: "Project scheme copied to clipboard!",
    tuningTable: "Wiring & Pin Allocation Matrix Table",
    tuningDesc: "You can change MCU pin mapping in the table, and the CAD wiring will redraw dynamically in real-time.",
    restoreBtn: "Restore AI Default Pins",
    conflictWarn: "Hardware GPIO Conflict Detected",
    conflictDesc: "Conflicting pin assignments found. Please select a different pin from the dropdown list to resolve conflicts:",
    mcuPin: "MCU Pin",
    peripheral: "Peripheral",
    peripheralPin: "Device Pin",
    signalType: "Signal Type",
    wireColor: "Wire Color",
    collisionTuning: "Wiring Description & Verification",
    conflictMessage: "Conflict: This pin is occupied by another device. Choose a different pin.",
    defaultPinDesc: "Connected MCU signal pin to operate the device.",
    bomTabTitle: "Bill of Materials (BOM)",
    bomTabDesc: "Core semiconductors and peripheral modules parsed from the wiring diagram. Export for Jialichuang (SZLCSC) or buy directly.",
    bomItemName: "Component Name",
    bomCNumber: "LCSC Part Number",
    bomQuantity: "Qty",
    bomPrice: "Est. Price",
    bomAction: "Purchase",
    bomCopyBtn: "Copy Shopping List",
    bomExportBtn: "Export LCSC BOM (CSV)",
    bomCopySuccess: "Shopping list copied to clipboard!",
    bomNotice: "Tip: Download the LCSC BOM CSV and upload it to JLCPCB/LCSC (https://bom.szlcsc.com/) to purchase all components in one click.",
    // CodeViewer
    codeTitle: "Generated C++ Firmware & Configuration Files",
    codeDesc: "The compilable firmware generated by the AI IoT Compiler. You can directly copy or download it.",
    copyFile: "Copy Current File",
    copySuccessFile: "File content copied successfully!",
    downloadZip: "Download Engineering ZIP",
    viewAllFiles: "View File Tree",
    dirTree: "Directory tree",
    copied: "Copied!",
    previewPlaceholder: "Select a file to preview",
    copyTree: "Copy File Tree",
    downloadZipBtn: "Download Project ZIP",
    treeCopiedAlert: "Directory tree copied!",
    compatNotice: "SUPPORT ARDUINO IDE • ESP-IDF • PLATFORMIO COMPILATION OUT-OF-THE-BOX",
    // DownloadCenter
    downloadTitle: "Learning Tasks and Feedback",
    downloadDesc: "Guides students through requirement analysis, component selection, interface recognition, virtual wiring, safety checks, code reading, export, and reflection while giving teachers a process-based feedback view.",
    noActiveProj: "No Teaching Project Generated",
    noActiveProjDesc: "Generate an IoT teaching project from Requirement Input first. The system will organize the teaching scaffold, project resources, and assessment tasks.",
    startNewProj: "Generate Teaching Project",
    resourcePackTitle: "Courseware Project Resource Pack",
    resourcePackDesc: "Includes firmware code, pin configuration, wiring notes, README, and export files for student tasks and teacher demonstrations.",
    zipFilenameDesc: "Includes driver headers, connections metadata, and project readme documentation",
    ready: "READY",
    fileCount: "Files count",
    fileCountVal: " files",
    unzipSize: "Size",
    mainPlatform: "MCU Type",
    sigVerification: "Signature Verification",
    shaVerified: "SHA-255 Verified",
    actionDownload: "Download Courseware Resource Pack",
    actionShare: "Share Project Link",
    shareSuccessAlert: "Project share link copied to clipboard. Other developers can open this URL to sync in real time.",
    stm32Notice: "Notice: The STM32 firmware utilizes Standard Peripheral Library (SPL) architecture with a complete directory tree (platformio.ini, delay, OLED). You can import directly to VSCode PlatformIO to compile and flash.",
    espNotice: "Notice: The ESP32 firmware uses the standard Arduino-compatible framework, including platformio.ini and complete program structure. You can import to VSCode PlatformIO or Arduino IDE directly.",
    wiringGuideTitle: "Physical Wiring Safety Guide",
    wiringGuideDesc: "Pins are allocated automatically based on electrical specifications. Please verify the following before powering on to prevent damage:",
    wiringGuideRule1: "Never mix 5V and 3.3V: ESP32 GPIOs tolerate max 3.3V. Feeding 5V directly to unprotected pins will permanently damage the MCU.",
    wiringGuideRule2: "Isolate High-Power Loads: Do not power servos, relays, or high-power LED strips directly from the MCU's 3.3V pin. Use an external power supply and share the GND.",
    wiringGuideRule3: "I2C Pull-ups: SDA and SCL buses require 4.7k or 10k pull-up resistors to 3.3V if the breakout board lacks them.",
    zipDetailsTitle: "ZIP Archive Directory Details",
    boardCompat: "MCU Compatibility",
    i2cRule: "I2C Routing",
    standardPinAlloc: "Standard Allocation",
    needModifyPinTitle: "Need to modify pin routing?",
    needModifyPinDesc: "You can click '2. Prompt Optimize' in the sidebar to change parameters, or input new constraints directly to the compiler.",
    modifyPromptBtn: "Tune Pin Mapping Prompts",
    // HistoryList
    confirmDelete: "Are you sure you want to delete this project scheme? This action is irreversible.",
    loginAuthTitle: "Please Sign In to Access Saved Schemes",
    loginAuthDesc: "Signing in syncs all schematics and code packages to a secure Firestore database, allowing cross-device access and retrieval.",
    historyTitle: "History Project Schemes",
    historyDesc: "Your generated hardware configurations and firmware codes saved in the cloud database.",
    syncCloudBtn: "Sync Cloud",
    syncingBtn: "Syncing...",
    loadingHistory: "Retrieving history records from database...",
    noHistory: "No History Projects",
    noHistoryDesc: "Submit your first design request. Successfully compiled schemes will save to the cloud automatically.",
    viewSchemeOnBoard: "Open Project Spec",
    deleteHistoryTitle: "Delete history item",
    // AdminPanel
    adminTitle: "IoT Platform Admin Control Panel",
    adminDesc: "Configure supported MCU databases, component dictionaries, wiring checks, and search audit logs.",
    demoEnvironment: "Demo Mode: Administrator Access Active",
    tabMcus: "1. MCU Database",
    tabComponents: "2. Components Dictionary",
    tabRules: "3. Wiring Validation Rules",
    tabTemplates: "4. Code Templates",
    tabAudits: "5. System Audit Logs",
    tabUsers: "6. User Accounts",
    mcuDbNotice: "The MCU database dictates default pin definitions, operating voltages, and ROM size guidelines.",
    addMcuBtn: "Add Board",
    mcuFormCancel: "Cancel",
    mcuFormSubmit: "Submit",
    mcuNameLabel: "MCU Model *",
    mcuFamilyLabel: "Processor Family",
    mcuSdaLabel: "SDA Pin (I2C)",
    mcuSclLabel: "SCL Pin (I2C)",
    mcuRomLabel: "ROM Size",
    mcuVoltageLabel: "Voltage",
    mcuTableColName: "MCU Model Name",
    mcuTableColFamily: "Family",
    mcuTableColPins: "I2C Pins",
    mcuTableColRom: "Flash ROM",
    mcuTableColVoltage: "Voltage",
    mcuTableColRecom: "Active Status",
    mcuTableColAction: "Actions",
    mcuActive: "Enabled",
    mcuInactive: "Disabled",
    deleteMcuTitle: "Delete Board",
    compDbNotice: "Manage peripheral component classifications, operating levels, pin counts, and technical specs.",
    addComponentBtn: "Add Component",
    compNameLabel: "Component Name *",
    compTypeLabel: "Interface Type",
    compCategoryLabel: "Category",
    compPinsLabel: "Pins Required",
    compVoltageLabel: "Level voltage",
    compDescLabel: "Pins descriptions",
    compFormSubmit: "Add Component",
    compTableColName: "Peripheral Name",
    compTableColCategory: "Category",
    compTableColType: "Interface",
    compTableColPins: "Pins",
    compTableColVoltage: "Voltage",
    compTableColDesc: "Description",
    compTableColStatus: "Status",
    compTableColAction: "Actions",
    compActive: "Active",
    compInactive: "Disabled",
    deleteCompTitle: "Delete Component",
    rulesNoticeTitle: "Auto Pin Verification Rules Active",
    rulesNoticeDesc: "Verification guidelines constraints applied to AI compilers. Colliding physical allocations are resolved dynamically.",
    rulesEspTitle: "Rule 1: ESP32 Boot Pin Restrictions",
    rulesEspDesc: "Peripherals must not be assigned to critical bootstrapping pins on boot, preventing hardware flash errors.",
    rulesEspList: "• GPIO 12 / MTDI (Boot strapping, pull low on powerup)\n• GPIO 15 / MTDO (Debugging, pull high on powerup)\n• GPIO 0 (Enter flashing mode on low level)\n• GPIO 34-39 (Input only pins, no output logic allowed)",
    rulesI2cTitle: "Rule 2: I2C Bus Address Restrictions",
    rulesI2cDesc: "When utilizing multiple I2C devices, address collision analysis is run across 7-bit registers.",
    rulesI2cList: "• OLED SSD1306 address: 0x3C (or 0x3D)\n• BMP280 Barometer address: 0x76 (or 0x77)\n• AHT20 Temp/Humid address: 0x38 (Static register)\n• PCA9685 PWM Controller address: 0x40 (Base address)",
    templateTitle: "Handlebars Output Templates",
    templateDesc: "Standard templates compiled to dynamically output C++ config headers based on pin constraints:",
    auditsNotice: "Audit logs tracking database actions, ZIP downloads, response performance metrics, and OAuth credentials.",
    auditsTableColUser: "User Email",
    auditsTableColAction: "Action",
    auditsTableColProj: "Project Name",
    auditsTableColPlatform: "MCU Platform",
    auditsTableColIp: "Remote IP",
    auditsTableColTime: "Timestamp",
    auditsTableColDetail: "Audit Message",
    auditsTableColStatus: "Status",
    // App empty states
    emptyStateTitle: "No Project Loaded for [{tabTitle}]",
    emptyStateDesc: "No active project is currently loaded. Go to Requirement Input to generate a new hardware prototype, or load the preset STM32 Greenhouse Simulation Lab.",
    emptyStateGoInput: "Go to [1. Requirement Input]",
    emptyStateLoadDemo: "Load Simulation Lab",
    demoTitle: "Smart IoT Greenhouse Automation System",
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>(() => {
    return (localStorage.getItem('lang') as Language) || 'zh';
  });

  const toggleLanguage = () => {
    const nextLang = lang === 'zh' ? 'en' : 'zh';
    setLang(nextLang);
    localStorage.setItem('lang', nextLang);
  };

  const t = (key: string): string => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
